export const mockData = [
  {
    id: 1,
    name: "John Smith",
    email: "john.smith@example.com",
    phone: "+1234567890",
    website: "https://www.johnsmith.com",
    image: "https://randomuser.me/api/portraits/men/1.jpg",
  },
  {
    id: 2,
    name: "Alice Johnson",
    email: "alice.johnson@example.com",
    phone: "+1234567891",
    website: "https://www.alicejohnson.com",
    image: "https://randomuser.me/api/portraits/women/2.jpg",
  },
  {
    id: 3,
    name: "Michael Brown",
    email: "michael.brown@example.com",
    phone: "+1234567892",
    website: "https://www.michaelbrown.com",
    image: "https://randomuser.me/api/portraits/men/3.jpg",
  },
  {
    id: 4,
    name: "Emily Wilson",
    email: "emily.wilson@example.com",
    phone: "+1234567893",
    website: "https://www.emilywilson.com",
    image: "https://randomuser.me/api/portraits/women/4.jpg",
  },
  {
    id: 5,
    name: "David Martinez",
    email: "david.martinez@example.com",
    phone: "+1234567894",
    website: "https://www.davidmartinez.com",
    image: "https://randomuser.me/api/portraits/men/5.jpg",
  },
  {
    id: 6,
    name: "Emma Taylor",
    email: "emma.taylor@example.com",
    phone: "+1234567895",
    website: "https://www.emmataylor.com",
    image: "https://randomuser.me/api/portraits/women/6.jpg",
  },
  {
    id: 7,
    name: "Matthew Anderson",
    email: "matthew.anderson@example.com",
    phone: "+1234567896",
    website: "https://www.matthewanderson.com",
    image: "https://randomuser.me/api/portraits/men/7.jpg",
  },
  {
    id: 8,
    name: "Olivia Garcia",
    email: "olivia.garcia@example.com",
    phone: "+1234567897",
    website: "https://www.oliviagarcia.com",
    image: "https://randomuser.me/api/portraits/women/8.jpg",
  },
  {
    id: 9,
    name: "Daniel Rodriguez",
    email: "daniel.rodriguez@example.com",
    phone: "+1234567898",
    website: "https://www.danielrodriguez.com",
    image: "https://randomuser.me/api/portraits/men/9.jpg",
  },
  {
    id: 10,
    name: "Sophia Martinez",
    email: "sophia.martinez@example.com",
    phone: "+1234567899",
    website: "https://www.sophiamartinez.com",
    image: "https://randomuser.me/api/portraits/women/10.jpg",
  },
  {
    id: 11,
    name: "Ethan Brown",
    email: "ethan.brown@example.com",
    phone: "+1234567810",
    website: "https://www.ethanbrown.com",
    image: "https://randomuser.me/api/portraits/men/11.jpg",
  },
  {
    id: 12,
    name: "Isabella Harris",
    email: "isabella.harris@example.com",
    phone: "+1234567811",
    website: "https://www.isabellaharris.com",
    image: "https://randomuser.me/api/portraits/women/12.jpg",
  },
  {
    id: 13,
    name: "Alexander Lee",
    email: "alexander.lee@example.com",
    phone: "+1234567812",
    website: "https://www.alexanderlee.com",
    image: "https://randomuser.me/api/portraits/men/13.jpg",
  },
  {
    id: 14,
    name: "Charlotte Clark",
    email: "charlotte.clark@example.com",
    phone: "+1234567813",
    website: "https://www.charlotteclark.com",
    image: "https://randomuser.me/api/portraits/women/14.jpg",
  },
  {
    id: 15,
    name: "William Young",
    email: "william.young@example.com",
    phone: "+1234567814",
    website: "https://www.williamyoung.com",
    image: "https://randomuser.me/api/portraits/men/15.jpg",
  },
  {
    id: 16,
    name: "Amelia Wright",
    email: "amelia.wright@example.com",
    phone: "+1234567815",
    website: "https://www.ameliawright.com",
    image: "https://randomuser.me/api/portraits/women/16.jpg",
  },
  {
    id: 17,
    name: "James Lopez",
    email: "james.lopez@example.com",
    phone: "+1234567816",
    website: "https://www.jameslopez.com",
    image: "https://randomuser.me/api/portraits/men/17.jpg",
  },
  {
    id: 18,
    name: "Ava Hall",
    email: "ava.hall@example.com",
    phone: "+1234567817",
    website: "https://www.avahall.com",
    image: "https://randomuser.me/api/portraits/women/18.jpg",
  },
  {
    id: 19,
    name: "Benjamin Moore",
    email: "benjamin.moore@example.com",
    phone: "+1234567818",
    website: "https://www.benjaminmoore.com",
    image: "https://randomuser.me/api/portraits/men/19.jpg",
  },
  {
    id: 20,
    name: "Grace Turner",
    email: "grace.turner@example.com",
    phone: "+1234567819",
    website: "https://www.graceturner.com",
    image: "https://randomuser.me/api/portraits/women/20.jpg",
  },
];
