export const mockData = [
  {
    id: 1,
    name: "John Doe",
    email: "john.doe@example.com",
    phone: "+1 (555) 123-4567",
    website: "www.johndoe.com",
    image: "https://placekitten.com/200/200",
    liked: false,
  },
  {
    id: 2,
    name: "Jane Smith",
    email: "jane.smith@example.com",
    phone: "+1 (555) 987-6543",
    website: "www.janesmith.com",
    image: "https://placekitten.com/201/201",
    liked: false,
  },
  {
    id: 3,
    name: "Bob Johnson",
    email: "bob.johnson@example.com",
    phone: "+1 (555) 789-0123",
    website: "www.bobjohnson.com",
    image: "https://placekitten.com/202/202",
    liked: false,
  },
  {
    id: 4,
    name: "Alice Williams",
    email: "alice.williams@example.com",
    phone: "+1 (555) 234-5678",
    website: "www.alicewilliams.com",
    image: "https://placekitten.com/203/203",
    liked: false,
  },
  {
    id: 5,
    name: "Michael Davis",
    email: "michael.davis@example.com",
    phone: "+1 (555) 876-5432",
    website: "www.michaeldavis.com",
    image: "https://placekitten.com/204/204",
    liked: false,
  },
  {
    id: 6,
    name: "Emily Miller",
    email: "emily.miller@example.com",
    phone: "+1 (555) 345-6789",
    website: "www.emilymiller.com",
    image: "https://placekitten.com/205/205",
    liked: false,
  },
  {
    id: 7,
    name: "David Taylor",
    email: "david.taylor@example.com",
    phone: "+1 (555) 789-0123",
    website: "www.davidtaylor.com",
    image: "https://placekitten.com/206/206",
    liked: false,
  },
  {
    id: 8,
    name: "Sophia Johnson",
    email: "sophia.johnson@example.com",
    phone: "+1 (555) 234-5678",
    website: "www.sophiajohnson.com",
    image: "https://placekitten.com/220/220",
    liked: false,
  },
  {
    id: 9,
    name: "Christopher Brown",
    email: "christopher.brown@example.com",
    phone: "+1 (555) 876-5432",
    website: "www.christopherbrown.com",
    image: "https://placekitten.com/208/208",
    liked: false,
  },
  {
    id: 10,
    name: "Olivia Davis",
    email: "olivia.davis@example.com",
    phone: "+1 (555) 345-6789",
    website: "www.oliviadavis.com",
    image: "https://placekitten.com/209/209",
    liked: false,
  },
  {
    id: 11,
    name: "Matthew White",
    email: "matthew.white@example.com",
    phone: "+1 (555) 789-0123",
    website: "www.matthewwhite.com",
    image: "https://placekitten.com/210/210",
    liked: false,
  },
  {
    id: 12,
    name: "Emma Harris",
    email: "emma.harris@example.com",
    phone: "+1 (555) 234-5678",
    website: "www.emmaharris.com",
    image: "https://placekitten.com/211/211",
    liked: false,
  },
  {
    id: 13,
    name: "Daniel Smith",
    email: "daniel.smith@example.com",
    phone: "+1 (555) 876-5432",
    website: "www.danielsmith.com",
    image: "https://placekitten.com/212/212",
    liked: false,
  },
  {
    id: 14,
    name: "Ava Martin",
    email: "ava.martin@example.com",
    phone: "+1 (555) 345-6789",
    website: "www.avamartin.com",
    image: "https://placekitten.com/213/213",
    liked: false,
  },
  {
    id: 15,
    name: "William Taylor",
    email: "william.taylor@example.com",
    phone: "+1 (555) 789-0123",
    website: "www.williamtaylor.com",
    image: "https://placekitten.com/214/214",
    liked: false,
  },
  {
    id: 16,
    name: "Isabella Clark",
    email: "isabella.clark@example.com",
    phone: "+1 (555) 234-5678",
    website: "www.isabellaclark.com",
    image: "https://placekitten.com/215/215",
    liked: false,
  },
  {
    id: 17,
    name: "James Johnson",
    email: "james.johnson@example.com",
    phone: "+1 (555) 876-5432",
    website: "www.jamesjohnson.com",
    image: "https://placekitten.com/216/216",
    liked: false,
  },
  {
    id: 18,
    name: "Mia Wilson",
    email: "mia.wilson@example.com",
    phone: "+1 (555) 345-6789",
    website: "www.miawilson.com",
    image: "https://placekitten.com/217/217",
    liked: false,
  },
  {
    id: 19,
    name: "Ethan Davis",
    email: "ethan.davis@example.com",
    phone: "+1 (555) 789-0123",
    website: "www.ethandavis.com",
    image: "https://placekitten.com/218/218",
    liked: false,
  },
  {
    id: 20,
    name: "Grace Thomas",
    email: "grace.thomas@example.com",
    phone: "+1 (555) 234-5678",
    website: "www.gracethomas.com",
    image: "https://placekitten.com/219/219",
    liked: false,
  },
];
